### ISSUE TITLE
Deployment failing 

### ISSUE THREAD

**Issue by GirtsZa** [vanderby/SonarQube-AzureAppService#62]
Hi, 

Deployment seems to be failing due to the fact that Deploy-SonarQubeAzureAppService.ps1 can't list the necessary image within sonarsource s3 bucket 

Error: Invoke-WebRequest : The remote server returned an error: (404) Not Found.\r\nAt C:\home\site\repository\Deploy-SonarQubeAzureAppService.ps1:83 char:25\r\n+ ... llDownloads = Invoke-WebRequest -Uri $downloadSource -UseBasicParsing\r\n+

Logs : 
[log.log](https://github.com/vanderby/SonarQube-AzureAppService/files/8133591/log.log)

Upon further inspection the when script tries to get $downloadSource it returns an empty object

**Comment by mevans-medpace** [comment]
I can confirm, I'm getting the same result.

**Comment by vanderby** [comment]
Looks like the issue is only when Version is `Latest` or blank. If you specify a version the script still works. The latest version is `9.3.0.51899`.

Looks like SQ moved to S3 buckets to host their binaries now and are using https://github.com/rufuspollock/s3-bucket-listing to display the list of files which doesn't play nicely with simply `Invoke-WebRequest` calls.

I'm open to suggestions on to better update the logic.
